### PR TITLE
Better automation for xzladder

### PR DESCRIPTION
**Pull request by JasonGross**
This merges master into `xzladder` for improvements to `specialize_by_assumption` and for `destruct_head'_sum` (rebasing would be better, but I didn't want to force-push to your branch, @andres-erbsen ).

On top of that, I've reworked the `t` tactic in `src/Curves/Montgomery/XZProofs.v` to be about twice as fast, moved a bit of the work of `fsatz` earlier so that each call to `fsatz` only takes 1-5 seconds (`Qed` takes around 26 seconds), and automated pretty much all of `projective_fst_xzladderstep`.  I left in a bunch of `Time` and `Profile` directives; feel free to strip them out or whatever.

### CODE REVIEW

**Comment by JasonGross** [comment]
Note that this is a PR against the `xzladder` branch, and not against master

**Comment by JasonGross** [comment]
Argh, apparently `nsatz` is better at the tip of `v8.6` than it is on released 8.6.... I'll separate out the improvements to `t` from the rest, and see what I can do about this

**Comment by JasonGross** [comment]
Now fixed

**Comment by andres-erbsen** [comment]
Merged into #162

**Pull request closed without merging**
