### PR TITLE
Add stacksize warnings to avoid confusion

### PR DESCRIPTION
**Pull request by JasonGross**
c.f. https://github.com/coq/platform/issues/178#issuecomment-1265444555

@andres-erbsen Does this seem like a good idea to you?

### CODE REVIEW

**Comment by andres-erbsen** [comment]
Sure. Please make the shell script use `-eu` so reading I can tell which commands' failure you're expecting to handle when reading it in order. In particular we should not break the build when `ulimit` is not available or errors on the request.

Also, could we just recommend `unlimited` instead of a large number?

**Comment by JasonGross** [comment]
> Sure. Please make the shell script use `-eu` so reading I can tell which commands' failure you're expecting to handle when reading it in order.

@andres-erbsen  Updated.  Is the current version better?

> In particular we should not break the build when `ulimit` is not available or errors on the request.

Subshell errors don't quit bash.  And anyway there's an `|| true` in the `Makefile`, so it's not going to break the build.  But I've made this more explicit in the script.

> Also, could we just recommend `unlimited` instead of a large number?

I want to not print this warning if the stack size is big enough.  Based on Coq's CI, the suggested number is big enough.  What's the benefit of recommending unlimited?

**Comment by andres-erbsen** [comment]
Sure, the script is now better: now I can see that you in fact want nonzero exit status when the desired ulimit setting is not detected. With the new factoring you might as well use printf instead of echo and variable substitution, but that's fine. I don't feel strongly about reocmmending unlimited; just any stack limit smaller than total memory limit seems silly for functional programming.

**Comment by JasonGross** [comment]
Note that this is the stack size required to compile our code with ocamlopt, not the stack required to run our code (which is less, I believe).

**Pull request merged**
