### PR TITLE
Reification machinery for adc, zselect

### PR DESCRIPTION
**Pull request by JasonGross**
This is on top of #170.

This adds reflective support for adc and zselect.  I haven't yet done pretty-printing for them; I figure I can do that when we actually have code coming out, so I can check my pretty-printer against actual code, rather than printing blindly.

@jadephilipoom `freeze_sig`, unlike the other `_sig` lemmas, takes a hypothesis for its correctness condition.  I don't know what to do with this when talking about field elements.  (Maybe we don't want to talk about field elements at all?)  I left you two `FIXME`s in `src/Specific/IntegrationTestFreeze.v`; can you fix them (and you might have to adapt the place where I use `freeze` before the reflective goal, too), and point me at a commit that I can cherry-pick onto this branch?  It should compile up to (but not including) the `Fail` line in that file (the `Fail` line takes a very, very long time to fail, because typeclasses and backtracking).

@jadephilipoom Can you update `freeze` to be in terms of the `zselect` and `add_get_carry` defined in `src/Util/ZUtil/Definitions.v`?

@andres-erbsen I left you with two goals which are all in terms of `Z` at the bottom of `src/Compilers/Z/Bounds/InterpretationLemmas/IsBoundedBy.v`.  I'm not sure that they are true; bounds analysis on add-get-carry might have to change.  Can you handle this?

### CODE REVIEW

**Comment by andres-erbsen** [comment]
I don't understand the current bounds analysis method. Here is how I think it should work for operations that produce multi-limb positional output: first use the bound propagation rule for the corresponding single-output operation to derive intermediate bounds, then express each output in terms of the intermediate value and use boundedness rules for division-by-constant and mod-by-constant to derive bounds on individual outputs. So there should be a proof that the version that uses a single intermediate result is equivalent to the original version, a lemma about bounds analysis of function composition, the boundedness proofs for div and mod, and the boundedness rule for the single-output variant which we presumably have already proven.

**Comment by JasonGross** [comment]
> I don't understand the current bounds analysis method.

That sounds like a bug.  Are you saying that you don't understand the infrastructure, or that you don't understand the (likely incorrect) bounds that I coded for add-get-carry?

> the boundedness rule for the single-output variant which we presumably have already proven.

Yes, the add-with-carry (`Z -> Z -> Z -> Z`) is proven by `{ apply (@monotone_eight_corners true true true _ _ _); split; auto. }`

> boundedness rules for division-by-constant and mod-by-constant

The division one is easy, since division is monotone.  What's the rule for mod-by-non-negative-constant?
```l ≤ x ≤ u → (if l / c =? u / c then Z.min (l mod c) (u mod c) else 0) ≤ x mod c ≤ (if l / c =? u / c then Z.max (l mod c) (u mod c) else Z.max 0 (c - 1))```?

**Comment by JasonGross** [comment]
@andres-erbsen Thanks for the hints; I've managed to get rid of the admit and prove boundedness for add-get-carry.

**Comment by andres-erbsen** [comment]
to derive bounds on `y = x mod m` given `a <= x < b`, `0 < m`:

1. adjust `a` and `b` by adding `k*m` to establish `0 <= a < m` (`y` unchanged)
2. if `0 <= a < b <= m`, return `a <= y < b` (`Zmod_small`)
3. otherwise return `0 <= y < m` (`Zmod_range`?). this is complete because we could have `a=m-1`, `b=m`.

**Comment by JasonGross** [comment]
@andres-erbsen I used slightly more general bounds description (basically the expression that I suggested above) that works even when `m` is 0 or negative; it uses the test `a / m = b / m` to ask if `0 <= k*m + a <= k*m + b < m` (for `a <= x <= b`), and then uses the fact that `k*m + a = a mod m` (and `k*m + b = b mod m`) if this is true.

**Comment by jadephilipoom** [comment]
The hypothesis on `freeze_sig` is the bounds precondition. I'm happy to rewrite it to whatever form makes it easiest for you to thread the bounds in.

**Comment by JasonGross** [comment]
> I'm happy to rewrite it to whatever form makes it easiest for you to thread the bounds in.

Currently it is `0 <= B.Positional.eval wt (BoundedWordToZ _ _ _ a) < 2 * Z.pos m`.  I need it to be a bunch of separate bounds on each limb of `(BoundedWordToZ _ _ _ a)`.  In particular, I need it to be of the form `is_bounded_by None bounds (BoundedWordToZ a)`.  I've updated the `(* FIXME(jadep) *) admit.` line to represent this; the goal is
```coq
is_bounded_by None bounds (map wordToZ a) -> 0 <= B.Positional.eval wt (map wordToZ a) < 2 * Z.pos m
```
or, after unfolding,
```coq
  ((((0 <= wordToZ (fst (fst (fst (fst a)))) <= 2533274790395904 /\ True) /\
     0 <= wordToZ (snd (fst (fst (fst a)))) <= 2533274790395904 /\ True) /\
    0 <= wordToZ (snd (fst (fst a))) <= 2533274790395904 /\ True) /\ 0 <= wordToZ (snd (fst a)) <= 2533274790395904 /\ True) /\
  0 <= wordToZ (snd a) <= 2533274790395904 /\ True ->
  0 <=
  B.Positional.eval wt
    (wordToZ (fst (fst (fst (fst a)))), wordToZ (snd (fst (fst (fst a)))), wordToZ (snd (fst (fst a))),
    wordToZ (snd (fst a)), wordToZ (snd a)) < 2 * Z.pos m
```
Can you fill this in?

**Comment by andres-erbsen** [comment]
I would guess that goes by some more `cbv` and then `omega`.

**Comment by jadephilipoom** [comment]
`freeze` is now in terms of your `add_get_carry` and `zselect`.

**Comment by JasonGross** [comment]
Great!  We can now reify freeze!*  Alas, there are still some issues:
1. You call `adc` with negative numbers, like `-2251799813685247`; hence the carry can be negative.  The reflective machinery only supports instructions producing unsigned integers.  What should be done?
2. The bit-width used for add-get-carry is 51.  As far as I know, this corresponds to no valid instruction on x86.  What should be done?
3. What's the right notation for Zselect?  Should I use `x == 0 ? a : b`?

* Here's the code that's printed:
```coq
λ x : word64 * word64 * word64 * word64 * word64,
Interp-η
(λ var : Syntax.base_type → Type,
 λ '(x7, x8, x6, x4, x2)%core,
 uint64_t x10, ℤ x11 = Op (Syntax.AddWithGetCarry 51 (Syntax.TWord 6) (Syntax.TWord 6) Syntax.TZ (Syntax.TWord 6) Syntax.TZ) (0x0, Return x2, Const (-2251799813685229));
 uint64_t x13, uint64_t x14 = Op (Syntax.AddWithGetCarry 51 (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6)) (0x0, 0x0, Return x10);
 ℤ x15 = x11 + x14;
 uint64_t x17, ℤ x18 = Op (Syntax.AddWithGetCarry 51 (Syntax.TWord 6) (Syntax.TWord 6) Syntax.TZ (Syntax.TWord 6) Syntax.TZ) (0x0, Return x4, Const (-2251799813685247));
 uint64_t x20, ℤ x21 = Op (Syntax.AddWithGetCarry 51 (Syntax.TWord 6) Syntax.TZ (Syntax.TWord 6) (Syntax.TWord 6) Syntax.TZ) (0x0, Return x15, Return x17);
 ℤ x22 = x18 + x21;
 uint64_t x24, ℤ x25 = Op (Syntax.AddWithGetCarry 51 (Syntax.TWord 6) (Syntax.TWord 6) Syntax.TZ (Syntax.TWord 6) Syntax.TZ) (0x0, Return x6, Const (-2251799813685247));
 uint64_t x27, ℤ x28 = Op (Syntax.AddWithGetCarry 51 (Syntax.TWord 6) Syntax.TZ (Syntax.TWord 6) (Syntax.TWord 6) Syntax.TZ) (0x0, Return x22, Return x24);
 ℤ x29 = x25 + x28;
 uint64_t x31, ℤ x32 = Op (Syntax.AddWithGetCarry 51 (Syntax.TWord 6) (Syntax.TWord 6) Syntax.TZ (Syntax.TWord 6) Syntax.TZ) (0x0, Return x8, Const (-2251799813685247));
 uint64_t x34, ℤ x35 = Op (Syntax.AddWithGetCarry 51 (Syntax.TWord 6) Syntax.TZ (Syntax.TWord 6) (Syntax.TWord 6) Syntax.TZ) (0x0, Return x29, Return x31);
 ℤ x36 = x32 + x35;
 uint64_t x38, ℤ x39 = Op (Syntax.AddWithGetCarry 51 (Syntax.TWord 6) (Syntax.TWord 6) Syntax.TZ (Syntax.TWord 6) Syntax.TZ) (0x0, Return x7, Const (-2251799813685247));
 uint64_t x41, ℤ x42 = Op (Syntax.AddWithGetCarry 51 (Syntax.TWord 6) Syntax.TZ (Syntax.TWord 6) (Syntax.TWord 6) Syntax.TZ) (0x0, Return x36, Return x38);
 ℤ x43 = x39 + x42;
 uint64_t x44 = x43 == 0 ? 0x0 : 0xffffffffffffffffL;
 uint64_t x45 = x44 & 0x7ffffffffffed;
 uint64_t x47, uint64_t x48 = Op (Syntax.AddWithGetCarry 51 (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6)) (0x0, Return x13, Return x45);
 uint64_t x50, uint64_t x51 = Op (Syntax.AddWithGetCarry 51 (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6)) (0x0, 0x0, Return x47);
 uint64_t x52 = x48 + x51;
 uint64_t x53 = x44 & 0x7ffffffffffff;
 uint64_t x55, uint64_t x56 = Op (Syntax.AddWithGetCarry 51 (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6)) (0x0, Return x20, Return x53);
 uint64_t x58, uint64_t x59 = Op (Syntax.AddWithGetCarry 51 (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6)) (0x0, Return x52, Return x55);
 uint64_t x60 = x56 + x59;
 uint64_t x61 = x44 & 0x7ffffffffffff;
 uint64_t x63, uint64_t x64 = Op (Syntax.AddWithGetCarry 51 (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6)) (0x0, Return x27, Return x61);
 uint64_t x66, uint64_t x67 = Op (Syntax.AddWithGetCarry 51 (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6)) (0x0, Return x60, Return x63);
 uint64_t x68 = x64 + x67;
 uint64_t x69 = x44 & 0x7ffffffffffff;
 uint64_t x71, uint64_t x72 = Op (Syntax.AddWithGetCarry 51 (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6)) (0x0, Return x34, Return x69);
 uint64_t x74, uint64_t x75 = Op (Syntax.AddWithGetCarry 51 (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6)) (0x0, Return x68, Return x71);
 uint64_t x76 = x72 + x75;
 uint64_t x77 = x44 & 0x7ffffffffffff;
 uint64_t x79, uint64_t x80 = Op (Syntax.AddWithGetCarry 51 (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6)) (0x0, Return x41, Return x77);
 uint64_t x82, uint64_t x83 = Op (Syntax.AddWithGetCarry 51 (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6)) (0x0, Return x76, Return x79);
 uint64_t _ = x80 + x83;
 (Return x82, Return x74, Return x66, Return x58, Return x50))
x
     : word64 * word64 * word64 * word64 * word64 → ReturnType (uint64_t * uint64_t * uint64_t * uint64_t * uint64_t)
```

**Comment by JasonGross** [comment]
> I would guess that goes by some more cbv and then omega.

Indeed, it does; thanks!

**Comment by JasonGross** [comment]
@jadephilipoom Shouldn't `freeze` be in terms of my `add_get_carry` only for the saturated case?

**Comment by jadephilipoom** [comment]
1. We need to determine how to represent signed integers. I discussed this with Andres some and we can probably avoid making large changes to the reification machinery. I'd call this a separate issue from reifying add-get-carry and zselect, which was what this test case was for.

2. This is kind of a toy test. As I mentioned in a comment on another issue, the 51-bit version would actually be done with shifts and ands. But word by word Montgomery is really where we'll use this, and there it will be 64-bit. I wanted you to reify the 51-bit version this way at first, just so we could see if it worked, but yes, eventually this should only reify as add-get-carry in the saturated case.

3. That notation is fine.

**Comment by JasonGross** [comment]
Notations updated; we now have:
```
λ x : word64 * word64 * word64 * word64 * word64,
Interp-η
(λ var : Syntax.base_type → Type,
 λ '(x7, x8, x6, x4, x2)%core,
 uint64_t x10, ℤ x11 = Op (Syntax.AddWithGetCarry 51 (Syntax.TWord 0) (Syntax.TWord 6) Syntax.TZ (Syntax.TWord 6) Syntax.TZ) (0x0, Return x2, Const (-2251799813685229));
 uint64_t x13, bool x14 = addcarryx_u51(0x0, 0x0, x10);
 ℤ x15 = x11 + x14;
 uint64_t x17, ℤ x18 = Op (Syntax.AddWithGetCarry 51 (Syntax.TWord 0) (Syntax.TWord 6) Syntax.TZ (Syntax.TWord 6) Syntax.TZ) (0x0, Return x4, Const (-2251799813685247));
 uint64_t x20, ℤ x21 = Op (Syntax.AddWithGetCarry 51 (Syntax.TWord 0) Syntax.TZ (Syntax.TWord 6) (Syntax.TWord 6) Syntax.TZ) (0x0, Return x15, Return x17);
 ℤ x22 = x18 + x21;
 uint64_t x24, ℤ x25 = Op (Syntax.AddWithGetCarry 51 (Syntax.TWord 0) (Syntax.TWord 6) Syntax.TZ (Syntax.TWord 6) Syntax.TZ) (0x0, Return x6, Const (-2251799813685247));
 uint64_t x27, ℤ x28 = Op (Syntax.AddWithGetCarry 51 (Syntax.TWord 0) Syntax.TZ (Syntax.TWord 6) (Syntax.TWord 6) Syntax.TZ) (0x0, Return x22, Return x24);
 ℤ x29 = x25 + x28;
 uint64_t x31, ℤ x32 = Op (Syntax.AddWithGetCarry 51 (Syntax.TWord 0) (Syntax.TWord 6) Syntax.TZ (Syntax.TWord 6) Syntax.TZ) (0x0, Return x8, Const (-2251799813685247));
 uint64_t x34, ℤ x35 = Op (Syntax.AddWithGetCarry 51 (Syntax.TWord 0) Syntax.TZ (Syntax.TWord 6) (Syntax.TWord 6) Syntax.TZ) (0x0, Return x29, Return x31);
 ℤ x36 = x32 + x35;
 uint64_t x38, ℤ x39 = Op (Syntax.AddWithGetCarry 51 (Syntax.TWord 0) (Syntax.TWord 6) Syntax.TZ (Syntax.TWord 6) Syntax.TZ) (0x0, Return x7, Const (-2251799813685247));
 uint64_t x41, ℤ x42 = Op (Syntax.AddWithGetCarry 51 (Syntax.TWord 0) Syntax.TZ (Syntax.TWord 6) (Syntax.TWord 6) Syntax.TZ) (0x0, Return x36, Return x38);
 ℤ x43 = x39 + x42;
 uint64_t x44 = (uint64_t) (x43 == 0 ? 0x0 : 0xffffffffffffffffL);
 uint64_t x46, bool x47 = addcarryx_u51(0x0, x13, x44 & 0x7ffffffffffed);
 uint64_t x49, bool x50 = addcarryx_u51(0x0, 0x0, x46);
 bool x51 = x47 + x50;
 uint64_t x53, bool x54 = addcarryx_u51(0x0, x20, x44 & 0x7ffffffffffff);
 uint64_t x56, bool x57 = addcarryx_u51(0x0, x51, x53);
 uint64_t x58 = (uint64_t) x54 + x57;
 uint64_t x60, bool x61 = addcarryx_u51(0x0, x27, x44 & 0x7ffffffffffff);
 uint64_t x63, bool x64 = addcarryx_u51(0x0, x58, x60);
 uint64_t x65 = (uint64_t) x61 + x64;
 uint64_t x67, bool x68 = addcarryx_u51(0x0, x34, x44 & 0x7ffffffffffff);
 uint64_t x70, bool x71 = addcarryx_u51(0x0, x65, x67);
 uint64_t x72 = (uint64_t) x68 + x71;
 uint64_t x74, bool x75 = addcarryx_u51(0x0, x41, x44 & 0x7ffffffffffff);
 uint64_t x77, bool x78 = addcarryx_u51(0x0, x72, x74);
 uint64_t _ = (uint64_t) x75 + x78;
 return (x77, x70, x63, x56, x49))
x
     : word64 * word64 * word64 * word64 * word64 → ReturnType (uint64_t * uint64_t * uint64_t * uint64_t * uint64_t)
```

@andres-erbsen Is it okay to have a few smatterings of using `bool` in various places where we're guaranteed that the output is at most one bit?

**Comment by JasonGross** [comment]
@jadephilipoom Do you have any objections to merging this now?  I'd like to not have to keep rebasing it on master (and if freeze isn't working perfectly, we can open issues / fix it later)

**Comment by JasonGross** [comment]
@jadephilipoom Can you do CSE on your side for `x44 & 0x7ffffffffffff`?  It'd be nice to have these masks dlet-bound, and not inlined into the adc, if that's doable.

**Comment by JasonGross** [comment]
> Can you do CSE on your side for x44 & 0x7ffffffffffff? It'd be nice to have these masks dlet-bound, and not inlined into the adc, if that's doable.

Oh, nevermind, you're free to do this or not; I thought it was interfering with the adc-rewriting transformation, but it's not.

**Comment by JasonGross** [comment]
superseded by #181

**Pull request closed without merging**
