### PR TITLE
Adapt to Coq's https://github.com/coq/coq/pull/7825

### PR DESCRIPTION
**Pull request by maximedenes**
To be merged after https://github.com/coq/coq/pull/7825 is merged.

### CODE REVIEW

**Comment by maximedenes** [comment]
Sorry, but the build time of fiat-crypto-legacy is too much for me, please improve the fix if it needs to be done. The Coq PR is critical for unifall, and have been delayed by more than 6-months because of fiat-crypto-legacy problems already.

> I thought `simple refine` was supposed to never shelve things

Before the Coq PR, holes in arguments of `simple refine` would be shelved if they were unified with already shelved variables (though not always, it used to depend on the orientation of evar-evar unification problems).

**Comment by JasonGross** [comment]
Okay, I will take a stab at fixing this within the next couple of days.  I suspect the fix I'll settle on is to use `[ shelve .. | | | | ]` with as many blank cases as there are expected goals.  (The issue is that there's one extra goal after this PR, right?) You don't happen to know the correct number of goals from your debugging session, do you?

**Comment by JasonGross** [comment]
Also, sorry fiat-crypto legacy is such a hassle.

**Comment by maximedenes** [comment]
Unfortunately, no, I could not determine if the number of goals was always the same. I studied only the first example where traces diverged.

> Also, sorry fiat-crypto legacy is such a hassle.

No worries, sorry to put the burden back on your shoulders. Shouldn't we consider tracking only the non-legacy version of fiat-crypto in our CI ? It could be better for everybody, I guess, no?

**Comment by JasonGross** [comment]
> Unfortunately, no, I could not determine if the number of goals was always the same. I studied only the first example where traces diverged.

The number of goals should always be the same.  It should be equal to the number of fields of the record being refined with.  My first attempt is going to be just blindly using that as the number of expected goals, and seeing if that builds.

> Shouldn't we consider tracking only the non-legacy version of fiat-crypto in our CI ? It could be better for everybody, I guess, no?

The legacy version is the only heavy test of the performance of printing that I'm aware of.  It is also a heavy tester of both the VM and unification, and I think these things are important to continue testing.  Speaking of testing, does the test-suite have a case that tests this change in which things are shelved vs not shelved in `simple refine`?

**Comment by maximedenes** [comment]
> The number of goals should always be the same. It should be equal to the number of fields of the record being refined with. My first attempt is going to be just blindly using that as the number of expected goals, and seeing if that builds.

Is the number of subgoals printed in ltac traces?

**Comment by maximedenes** [comment]
> The legacy version is the only heavy test of the performance of printing that I'm aware of. It is also a heavy tester of both the VM and unification, and I think these things are important to continue testing.

Sure, but unification is well tested by other developments (it would still benefit a lot from having a spec and a suite of functional tests, but that's another story). For the VM, I'd need to check. Has the non-legacy version of fiat-crypto stopped using it?

For printing, I understand the idea, but it seems to me that having to explore millions of lines of ltac traces just to fix a tactic bug, finally realizing that the original script was relying on the bug is not a good trade-off. There must be a more optimal way of testing the performance of printing.

**Comment by JasonGross** [comment]
> Has the non-legacy version of fiat-crypto stopped using it?

Mostly, yes.  The new version mostly relies on extraction + ocamlopt, though we do still use the VM in a couple of places for smaller tests.

> For printing, I understand the idea, but it seems to me that having to explore millions of lines of ltac traces just to fix a tactic bug, finally realizing that the original script was relying on the bug is not a good trade-off. There must be a more optimal way of testing the performance of printing.

Indeed.  Though do you really need to explore the millions of lines?  If you `Set Ltac Debug. Set Ltac Batch Debug.` and pipe the output into a file with Coq just before and just after the relevant PR, and then run `vimdiff` on the resulting files, shouldn't that highlight just the location where the traces diverge?

One possibility for testing printing is to copy over the inductive declarations and notations from fiat-crypto legacy, and then copy-paste the `Set Printing All` AST from a bunch of the tests.

**Comment by JasonGross** [comment]
I'll merge once the CI passes

**Comment by JasonGross** [comment]
https://github.com/coq/coq/pull/7825 was merged without needing this overlay, so I will close without merging

**Pull request closed without merging**
