### PR TITLE
Adapt to coq/coq#17274 (Eval prints evar info like Check)

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by andres-erbsen** [comment]
@JasonGross @jadephilipoom Now that we test that montladder compiles to RISC-V, perhaps it makes sense to just remove this file?

**Comment by JasonGross** [comment]
> perhaps it makes sense to just remove this file?

That seems reasonable.  The other backwards-compatible change is to adapt the `sed` script in the Makefile to remove `^where$$` and `^?.*`

**Comment by ppedrot** [comment]
If you guys are going to remove it upstream, please close this overlay when that happens.

**Comment by ppedrot** [comment]
Please merge now.

**Comment by andres-erbsen** [comment]
I created https://github.com/mit-plv/fiat-crypto/pull/1579 and set it to merge upon CI success. Let's not merge this PR as it does not pass CI.

**Pull request closed without merging**
