### PR TITLE
Optimize dettman algorithm

### PR DESCRIPTION
**Pull request by OwenConoly**
This implements the optimization described in #1582.

This should resolve almost all of #1582; the only thing missing is the aesthetic improvement mentioned [here](https://github.com/mit-plv/fiat-crypto/commit/b7798cb03a6ecd597d2fb5f55c2b67cba6347d93#r111587543) about removing an unnecessary & operation, which I don't know how to fix.

Incidentally, I've realized that the dettman template, in its state before this PR, did unreasonable things when given a fractional limbwidth.  I've rewritten it so that it will hopefully---I haven't tested this or anything---now behave reasonably given a fractional limbwidth.  This happened to require the same sort of change that I was making to implement the optimization.  This change should make the algorithm a bit easier to read, too.

### CODE REVIEW

**Comment by dderjoel** [comment]
FWIW, I am unsure if the current files in [fiat-amd64/fiat_secp256k1_dettman_mul ](https://github.com/mit-plv/fiat-crypto/tree/master/fiat-amd64/fiat_secp256k1_dettman_mul) (and square respectively) would still be proven correct.
I've updated the files in [CryptOpt](https://github.com/0xADE1A1DE/CryptOpt/tree/main/generated/secp256k1) already. Feel free to replace them, in case the validation does not succeed. I can then later provide the 3-best-per-architechture files just like for the other curves.

**Comment by OwenConoly** [comment]
Ah!  I forgot about updating those.  Indeed, they [failed](https://github.com/mit-plv/fiat-crypto/actions/runs/4876486620/jobs/8702345705?pr=1601).  I'll replace them with the CryptOpt files that you linked.

**Comment by OwenConoly** [comment]
I'm trying to add [this](https://github.com/mit-plv/fiat-crypto/commit/b7798cb03a6ecd597d2fb5f55c2b67cba6347d93#r111587543) enhancement, via a new and/or generalized rewriting rule, before merging this PR.
I've added some commits to this branch where I make some attempts at progress on that, so this branch is no longer in a good state to merge.

**Comment by OwenConoly** [comment]
The dettman code generation actually works now (with the redundant `&` removed!), but the new rewriting pass that I've added has broken some other things.

Code generation for `fiat-c/src/p521_32.c` (among others, I assume) doesn't work---the error is with "converting to C", as you can see in [the build of my most recent commit](https://github.com/mit-plv/fiat-crypto/actions/runs/5006935804/jobs/8972875948?pr=1601).

@andres-erbsen, @JasonGross - do you have any idea what would cause this?  Might it be the same issue as in https://github.com/mit-plv/fiat-crypto/issues/1604?

**Comment by OwenConoly** [comment]
Oops, never mind my previous comment.  I've inferred (correctly, I think?) from #1604 that my problem has something to do with dead code elimination, so I've removed the dead code elimination thing that I added in `BoundsPipeline.v`.  This seems to have fixed the issue.

**Comment by OwenConoly** [comment]
Looks like the redundant ands, which are removed by the new rewrite pass that I added, actually appeared in a lot of places other than the dettman code.  Adding the new rewrite pass caused the total length of generated code to decrease by about 27000 lines.  I was not expecting this, but I think it's a good thing.

**Comment by andres-erbsen** [comment]
This cleanup is indeed more impressive than anticipated :D. Great job!

**Review by JasonGross — APPROVED** [review]
Other than needing to update one more 3 into 4 for accurate error messages, this looks good to me!

**Pull request merged**
