### PR TITLE
Moved Ncring_Ring instance at the top, to simplify few proofs

### PR DESCRIPTION
**Pull request by mukeshtiwari**
@JasonGross  I moved Ncring_Ring instance at the top, to simply some of your proofs [1]. 

[1] https://coq.inria.fr/library/Coq.setoid_ring.Ncring.html

### CODE REVIEW

**Review by JasonGross — APPROVED** [review]
Thanks!  I'll merge if the CI is happy

**Comment by JasonGross** [comment]
Could you rebase this on top of the current master so that the CI has a chance to pass on Coq's master branch?  Sorry for the delay in starting the CI.

**Comment by mukeshtiwari** [comment]
Hi @JasonGross, sorry I did not get "'rebase this on top of the current master" (sorry, not much of expert in git).  Based on my understanding of rebase, which is not very solid, I pushed changes in the master branch and then created the pull request, so I am not sure how to rebase the my master with your current master. Can you tell me how to do this?

**Comment by JasonGross** [comment]
No worries, I've done the rebase and force-pushed for you.  There's some documentation about the thing I was asking you to do at https://docs.github.com/en/get-started/using-git/about-git-rebase, and the particular commands to use would be something like `git remote add upstream https://github.com/mit-plv/fiat-crypto && git remote update && git rebase upstream/master && git push --force-with-lease origin master`.  (But, again, I've done this for this PR and there's not need for you to do it.)

**Comment by mukeshtiwari** [comment]
Thanks @JasonGross. I will keep that in mind in future pull request.

**Pull request merged**
