### PR TITLE
Make [reflect] a typeclass and add a bunch of lemmas

### PR DESCRIPTION
**Pull request by JasonGross**

### CODE REVIEW

**Comment by andres-erbsen** [comment]
Isn't reflect superseded by boolspec? @samuelgruetter

**Comment by JasonGross** [comment]
Is boolspec a thing in fiat-crypto?

**Comment by andres-erbsen** [comment]
```coq
Require Import ZArith.
Search BoolSpec.
(* BoolSpecF: forall P Q : Prop, Q -> BoolSpec P Q false *)
(* BoolSpecT: forall P Q : Prop, P -> BoolSpec P Q true *)
(* Nat.ltb_spec: forall x y : nat, BoolSpec (x < y) (y <= x) (x <? y) *)
(* Z.geb_spec: forall n m : Z, BoolSpec (m <= n)%Z (n < m)%Z (n >=? m)%Z *)
(* Z.gtb_spec: forall n m : Z, BoolSpec (m < n)%Z (n <= m)%Z (n >? m)%Z *)
(* Pos.ltb_spec: *)
(*   forall x y : positive, BoolSpec (x < y)%positive (y <= x)%positive (x <? y)%positive *)
(* Z.leb_spec: forall x y : Z, BoolSpec (x <= y)%Z (y < x)%Z (x <=? y)%Z *)
(* Z.ltb_spec: forall x y : Z, BoolSpec (x < y)%Z (y <= x)%Z (x <? y)%Z *)
(* Pos.leb_spec: *)
(*   forall x y : positive, BoolSpec (x <= y)%positive (y < x)%positive (x <=? y)%positive *)
(* N.ltb_spec: forall x y : N, BoolSpec (x < y)%N (y <= x)%N (x <? y)%N *)
(* Nat.leb_spec: forall x y : nat, BoolSpec (x <= y) (y < x) (x <=? y) *)
(* N.leb_spec: forall x y : N, BoolSpec (x <= y)%N (y < x)%N (x <=? y)%N *)
(* ring stuff... *)
```

@samuelgruetter IIRC you looked into BoolSpec vs alternatives, what did you conclude?

**Comment by JasonGross** [comment]
After in person discussion: no strong preferences, so I'll merge this as-is because I've done the work for `reflect` already.  (Differences: `BoolSpec` lets you specify different true and false props (I can't imagine when we'd want this); `BoolSpec` lives in `Prop` (only pro I can think of: this lets you do `setoid_rewriting` with `iff` when your goal is `BoolSpec ...` without requiring CSetoids or whatever) while `reflect` lives in `Set`)

**Pull request merged**
