### PR TITLE
Garagedoor Prettification

### PR DESCRIPTION
**Pull request by samuelgruetter**
I forgot about this in the hurry of paper writing but I think it should be merged before it gets stale.

### CODE REVIEW

**Comment by samuelgruetter** [comment]
One [CI task](https://github.com/mit-plv/fiat-crypto/actions/runs/4840182998/jobs/8625669497?pr=1598) fails with
```
make: *** No rule to make target 'rewriter', needed by 'deps'.  Stop.
+ (etc/ci/github-actions-make.sh @ line 46) $ exit 2
```
even though I rebased on master, and that failure doesn't appear on master. Any idea what this could be @JasonGross ?

**Comment by JasonGross** [comment]
The problem with `-j2` is that it keeps going after [the actual error, which is](https://github.com/mit-plv/fiat-crypto/actions/runs/4840182998/jobs/8625669497?pr=1598#step:6:2393)
```
File "./src/Rewriter/Util/plugins/Ltac2Extra.v", line 8, characters 21-34:
Error: Unregistered primitive "ltac2" "constr_equal_nounivs"

Command exited with non-zero status 1
src/Rewriter/Util/plugins/Ltac2Extra.vo (real: 0.13, user: 0.07, sys: 0.05, mem: 109152 ko)
Error: make[2]: *** [Makefile.coq:824: src/Rewriter/Util/plugins/Ltac2Extra.vo] Error 1
Error: make[1]: *** [Makefile.coq:409: all] Error 2
```
If you search the logs for `Error: make`, you can find this.  I guess we need to merge https://github.com/mit-plv/rewriter/pull/101 and bump the submodule, I'll set https://github.com/mit-plv/rewriter/pull/101 to merge

**Comment by JasonGross** [comment]
#1599 should auto-merge once CI passes, if you rebase on top of that, it should fix the build issue

**Comment by JasonGross** [comment]
Unluckily, we also need to rebase on #1600

**Pull request merged**
