### PR TITLE
Add non-building Opp reification

### PR DESCRIPTION
**Pull request by JasonGross**
I'd like to reify `opp`.  Currently, `opp_sig` uses `Z.opp`, which is not a supported operation.  @jadephilipoom can you fix that, and then make sure that this builds on top of your fix, and then merge this (or let me know and I can merge it)?

### CODE REVIEW

**Comment by andres-erbsen** [comment]
Why does the synthesis output contain `opp` anyway. Should it?

**Comment by JasonGross** [comment]
It contains expressions like `x + 1 * (1 * (1 * -y + 0))`  @jadephilipoom can say more

**Comment by JasonGross** [comment]
Also, this is fixed with #149, where I add support for `Z.opp` in the reifier and the expression simplifier which can (hopefully) make it go away.

**Comment by andres-erbsen** [comment]
Hmm. I think it is fine to leave negation-elimination to the reflective tactics, but doing so shouldn't introduce a dependency on old BaseSystem.

**Comment by andres-erbsen** [comment]
Looking at Z.syntax, I think `Neg` should go away and we should use `Opp` instead.

**Comment by JasonGross** [comment]
Sure, we can remove `Neg`; maybe save it for the cleaning when we decide what to do with cmovle and cmovne?

**Comment by JasonGross** [comment]
This PR is no longer needed, since we have a test with sub

**Pull request closed without merging**
