### PR TITLE
Fix a typo, present in all generated files

### PR DESCRIPTION
**Pull request by jedisct1**

### CODE REVIEW

**Comment by JasonGross** [comment]
Ooh, thanks!  Could you also fix the generated files; otherwise the CI will fail complaining that they've not been regenerated.

**Comment by jedisct1** [comment]
Hi Jason,

Of course! Done.

**Comment by JasonGross** [comment]
According to the CI, the fiat-java files still need to be fixed.  (And don't forget the fiat-bedrock2.). I'd suggest just running `git ls-files | xargs sed -i 's/bad spelling/good spelling/g'` to get all the files in the repo.

**Comment by jedisct1** [comment]
CI's green :)

**Comment by JasonGross** [comment]
Thanks again!

**Pull request merged**
