### PR TITLE
add Alpine CI

### PR DESCRIPTION
**Pull request by andres-erbsen**

### CODE REVIEW

**Comment by andres-erbsen** [comment]
[`ocamlfind: Package `coq-core.plugins.ltac' not found`](https://github.com/mit-plv/fiat-crypto/actions/runs/5675163948/job/15379985109?pr=1625#step:4:357) :(

**Comment by andres-erbsen** [comment]
It's not feature-complete wrt the Ubuntu LTS CI, but we could say we want it anyway.

**Comment by JasonGross** [comment]
@andres-erbsen I'm looking into what it would take to automatically publish standalone binaries on releases, and it seems like we'd probably want alpine for this.  Should we merge this?

**Comment by andres-erbsen** [comment]
I don't have a vision here, i'd be happy if you adopted this one.

**Pull request merged**
