### PR TITLE
Remove the axiom in Curves/Edwards/AffineProofs

### PR DESCRIPTION
**Pull request by JasonGross**
This will make progress towards #736

@andres-erbsen Please comment on my naming, and whether `of_Z_absorbs_homomorphism` seems okay, or if there's a different name you'd suggest

### CODE REVIEW

**Comment by andres-erbsen** [comment]
I can't think of a great name here. `two_homomorphisms_of_Z` is an alternative that comes to mind.

**Comment by JasonGross** [comment]
Hm, I think I'll leave it as is, if you're okay with that.  (It's not clear to me how `two_homomorphisms_of_Z` describes what's going on here.)

**Comment by andres-erbsen** [comment]
how does the current name describe what's going on? I think it's fine as an arbitrary name, though

**Comment by JasonGross** [comment]
It says that when you compose `of_Z` with ring homomorphisms, the homomorphisms are "absorbed" into the `of_Z`.

**Comment by JasonGross** [comment]
Hmmm, maybe a better factoring of this proof would be proving that the composition of two homomorphisms is a homomorphism (do we have this already?), and proving that any two ring homomorphisms out of `Z` are pointwise-equal?  (i.e., proving that `Z` is the initial ring)  Anyway, that's a task for the future

**Pull request merged**
