### PR TITLE
Test Rust on travis

### PR DESCRIPTION
**Pull request by JasonGross**
@zoep is "nightly" the right version of the Rust compiler to use?

### CODE REVIEW

**Comment by zoep** [comment]
Should build with stable too since we’re not relying on nightly features, but nightly is fine too (and the one I used to build/test them).

**Comment by JasonGross** [comment]
You don't need nightly for 128-bit integers?  I thought I saw a comment to that effect...

**Comment by zoep** [comment]
> You don't need nightly for 128-bit integers? I thought I saw a comment to that effect...

Ah sorry this comment is outdated and I'll be removing it, they've been integrated to stable since 1.26.

**Comment by JasonGross** [comment]
Ah, great, I'll test on stable then

**Pull request merged**
