### PR TITLE
Clean up montladder code and update for rupicola master.

### PR DESCRIPTION
**Pull request by DIJamner**
Improves the presentation of the montladder proofs.

### CODE REVIEW

**Comment by andres-erbsen** [comment]
```
File "./src/Bedrock/Group/ScalarMult/MontgomeryEquivalence.v", line 38, characters 36-50:
Error: The reference Notations.nlet was not found in the current environment.

Command exited with non-zero status 1
src/Bedrock/Group/ScalarMult/MontgomeryEquivalence.vo (real: 1.75, user: 1.26, sys: 0.41, mem: 583512 ko)
make: *** [src/Bedrock/Group/ScalarMult/MontgomeryEquivalence.vo] Error 1
make: *** Waiting for unfinished jobs....
fiat-bedrock2/src/p384_32.c (real: 531.03, user: 523.57, sys: 4.35, mem: 1329544 ko)
(rm fiat-bedrock2/src/p384_32.c.ok && mv fiat-bedrock2/src/p384_32.c.tmp fiat-bedrock2/src/p384_32.c) || ( RV=$?; cat fiat-bedrock2/src/p384_32.c.tmp; exit $RV )
+ exit 2
Error: Process completed with exit code 2.
```

so the next person looking at this won't spend time digging through the logs.

**Comment by DIJamner** [comment]
This branch should be fixed up, but the builds are failing with what appear to be large diffs of fiat-generated c code. This PR shouldn't touch that code other than by bumping rupicola (and therefore bedrock). @andres-erbsen, @samuelgruetter, or anyone else, does this seem connected to bedrock changes and if so, what's the fix?

**Comment by samuelgruetter** [comment]
Looks like this is due to recent changes to [this prelude](https://github.com/mit-plv/bedrock2/blob/045a0052311d3971aae57f43173ae73f66eef3df/bedrock2/src/bedrock2/ToCString.v#L6-L32). I didn't write that code, but how about putting that prelude into a separate `bedrock2_prelude.h`, so that individual files would only contain `#include "bedrock2_prelude.h"`?

**Comment by DIJamner** [comment]
Thanks for the pointer, and your solution definitely sounds good long-term. For now, since we know where the change is coming from, I think I'll see if I can figure out how to update the test files to agree with the output, since they will need to change either way. Hopefully that will get this build passing sooner.

**Comment by JasonGross** [comment]
>  I think I'll see if I can figure out how to update the test files to agree with the output, since they will need to change either way

I think `make bedrock2-files` and then commit the generated files should do it

**Comment by JasonGross** [comment]
Do you have a different version of bedrock2 locally than the one that's checked in here?
```diff
@@ -18,46 +18,30 @@
 /*                            if x1 & (2^256-1) < 2^255 then x1 & (2^256-1) else (x1 & (2^256-1)) - 2^256 */
 
 #include <stdint.h>
+#include <string.h>
 
-// We use bytewise access to work around -fstrict-aliasing.
-// On clang 10, these functions could be replaced with memcpy but gcc 11
-// seems to fail to infer the bounds on an integer loaded by memcpy.
+// We use memcpy to work around -fstrict-aliasing.
+// A plain memcpy is enough on clang 10, but not on gcc 10, which fails
+// to infer the bounds on an integer loaded by memcpy.
 // Adding a range mask after memcpy in turn makes slower code in clang.
-// The little-endian memory access idioms below are fast in both.
-static inline uintptr_t _br2_load(uintptr_t a, uintptr_t sz) {
-  uint8_t* p = (uint8_t*) a;
-  uintptr_t r = 0;
+// Loading individual bytes, shifting them together, and or-ing is fast
+// on clang and sometimes on GCC, but other times GCC inlines individual
+// byte operations without reconstructing wider accesses.
+// The little-endian idiom below seems fast in gcc 9+ and clang 10.
+static __attribute__((always_inline)) inline uintptr_t
+_br2_load(uintptr_t a, uintptr_t sz) {
   switch (sz) {
-    case 8: r |= (uintptr_t)p[7] << 56;
-            r |= (uintptr_t)p[6] << 48;
-            r |= (uintptr_t)p[5] << 40;
-            r |= (uintptr_t)p[4] << 32;
-            // fall through
-    case 4: r |= (uintptr_t)p[3] << 24;
-            r |= (uintptr_t)p[2] << 16;
-            // fall through
-    case 2: r |= (uintptr_t)p[1] << 8;
-            // fall through
-    case 1: r |= (uintptr_t)p[0];
+  case 1: { uint8_t  r = 0; memcpy(&r, (void*)a, 1); return r; }
+  case 2: { uint16_t r = 0; memcpy(&r, (void*)a, 2); return r; }
+  case 4: { uint32_t r = 0; memcpy(&r, (void*)a, 4); return r; }
+  case 8: { uint64_t r = 0; memcpy(&r, (void*)a, 8); return r; }
+  default: __builtin_unreachable();
   }
-  return r;
 }
```

**Comment by DIJamner** [comment]
Thanks for the pointers. Assuming all checks pass, this should be ready to merge.

**Comment by JasonGross** [comment]
All checks pass :tada:

**Pull request merged**
