### PR TITLE
Add some documentation to README about the new pipeline

### PR DESCRIPTION
**Pull request by JasonGross**
The documentation is very minimal at the moment, but I plan to update it
with more details in the near future.

cc @agl @davidben

### CODE REVIEW

**Comment by agl** [comment]
Following the [README.md from in the second commit](https://github.com/mit-plv/fiat-crypto/blob/56f9b8bcc512c35d43789da9f546d5f204c15d23/README.md):

```sh
$ coqc --version
The Coq Proof Assistant, version 8.8.1 (August 2018)
compiled on Aug 14 2018 7:28:08 with OCaml 4.07.0
```

Probably ok, although it's 8.8.1 rather than 8.8.0 that the README say has been tested.

> To build (if your COQPATH variable is empty):
> make

```sh
$ echo $COQPATH

```

Ok, looks empty. Let's try `make`:

```sh
$ make
COQ_MAKEFILE -f _CoqProject > Makefile.coq
make: execvp: /bin/sh: Argument list too long
make: execvp: /bin/sh: Argument list too long
make: execvp: /bin/sh: Argument list too long
make: *** No rule to make target 'bbv/theories/BinNotation.v', needed by 'bbv/theories/BinNotation.vo'.  Stop.
```

Hmm. `strace` does show a huge argument list that includes things like &ldquo;&hellip;src/Specific/solinas64_2e130m5_3limbs/fesub.vo src/Specific/solinas64_2e130m5_3limbs/fesubDisplay.vo&hellip;&rdquo;

**Comment by JasonGross** [comment]
@agl Thanks.  I've updated the build instructions with the lines

> If you checked out this repository via `git`, you should run
>
>     git submodule update --init --recursive
>
>[...]
>
>You may get non-fatal errors such as `make: execvp: /bin/sh: Argument list too long`; this is an artifact of the [old pipeline](#old-pipeline) and is a [bug in Coq](https://github.com/coq/coq/issues/7584) that will prevent `make install` from succeeding, but will not impact the build itself.

**Comment by JasonGross** [comment]
Btw, @agl, the timing info is currently available in the commit messages of bb58c1eb9accfc6bfd849fa10909df7db3158e1a and 98d5728e328943da278bd98a46248a12f23b7fc0.  It takes about 95 minutes to build the entire library in serial (actually a bit more, since this is user-time reported by Coq and doesn't include the `par:` tactic that does some heavy lifting in a couple of proofs), and about 22 minutes to build just the C files in serial.  The slowest files in the path to building C files are
```

Time      | File Name
------------------------------------------------------------------------------
21m56.29s | Total
------------------------------------------------------------------------------
4m33.00s  | Experiments/NewPipeline/Toplevel1.vo
3m56.42s  | Experiments/NewPipeline/RewriterRulesGood.vo
1m30.76s  | Experiments/NewPipeline/Arithmetic.vo
1m16.62s  | Experiments/NewPipeline/RewriterWf2.vo
1m16.43s  | Experiments/NewPipeline/Rewriter.vo
0m41.70s  | Experiments/NewPipeline/AbstractInterpretationWf.vo
0m38.28s  | p521_32.c
0m35.89s  | Experiments/NewPipeline/LanguageInversion.vo
0m35.72s  | Experiments/NewPipeline/ExtractionOCaml/word_by_word_montgomery
0m31.76s  | p521_64.c
0m25.04s  | Experiments/NewPipeline/UnderLetsProofs.vo
0m23.98s  | p384_32.c
0m22.29s  | Experiments/NewPipeline/AbstractInterpretationZRangeProofs.vo
0m22.23s  | Experiments/NewPipeline/LanguageWf.vo
0m18.46s  | Experiments/NewPipeline/ExtractionOCaml/unsaturated_solinas
0m15.14s  | Algebra/Field.vo
0m13.10s  | Experiments/NewPipeline/CStringification.vo
0m12.23s  | Experiments/NewPipeline/AbstractInterpretationProofs.vo
0m12.14s  | Util/ZRange/LandLorBounds.vo
0m11.77s  | Experiments/NewPipeline/GENERATEDIdentifiersWithoutTypesProofs.vo
0m10.20s  | Algebra/Ring.vo
```

**Comment by JasonGross** [comment]
Going to merge this now, but @agl feel free to comment with more problems/requests/whatever

**Pull request merged**
