### PR TITLE
Integrate elimination of useless carries

### PR DESCRIPTION
**Pull request by JasonGross**
Alas, we are now too slow for Travis, I believe, even on 8.5.  (Dealing with things with 90 binders is slow.)

Timing data coming soon.

### CODE REVIEW

**Comment by JasonGross** [comment]
Updated; no more admitted proofs, and I've inspected the extraction and it looks fine, modulo doing lots of stuff with pairs/tuples, and calling `Prelude.fst` and `Prelude.snd` in some places.

**Comment by JasonGross** [comment]
Updated with timing: the core stuff takes about 20 minutes; the entire library with SpecificGen takes around 2 hours.  The most expensive files, RAM-wise, are:
```
3833012 ko: src/Specific/GF25519Reflective/Common9_4Op (real: 144.97, user: 144.50, sys: 0.43
3900312 ko: src/SpecificGen/GF25519_32Reflective/Common9_4Op (real: 147.31, user: 146.41, sys: 0.41
4054572 ko: src/SpecificGen/GF2519_32Reflective/Common9_4Op (real: 148.13, user: 147.71, sys: 0.44
4787988 ko: src/SpecificGen/GF41417_32Reflective/Reified/AddCoordinates (real: 774.85, user: 772.27, sys: 2.19
4981020 ko: src/SpecificGen/GF41417_32Bounded (real: 153.96, user: 152.78, sys: 1.20
5389704 ko: src/SpecificGen/GF41417_32Reflective/Reified/Mul (real: 59.80, user: 59.16, sys: 0.50
6849868 ko: src/SpecificGen/GF5211_32Bounded (real: 212.85, user: 212.18, sys: 0.72
7322204 ko: src/SpecificGen/GF5211_32Reflective/Reified/AddCoordinates (real: 2041.49, user: 2036.77, sys: 3.04
15851240 ko: src/SpecificGen/GF41417_32Reflective/Common9_4Op (real: 911.82, user: 906.36, sys: 5.37
23160552 ko: src/SpecificGen/GF5211_32Reflective/Common9_4Op (real: 1307.24, user: 1303.91, sys: 2.50
26437792 ko: src/SpecificGen/GF5211_32Reflective/Reified/Mul (real: 274.07, user: 270.01, sys: 3.97
```

The core things now need about 4 GB of RAM to build, and SpecificGen still needs around 27 GB of RAM to build.

**Comment by andres-erbsen** [comment]
I assume this is stale and should be closed?

**Comment by JasonGross** [comment]
Yes

**Pull request closed without merging**
