### PR TITLE
Zig Fiat-Crypto-generated code is now continuously tested

### PR DESCRIPTION
**Pull request by jedisct1**
The first bits of Fiat-generated code have landed into the Zig standard library.

The code is now continuously tested on all supported platforms.

### CODE REVIEW

**Comment by JasonGross** [comment]
That's great to hear!

I'd like to reserve the heavy checkmark for tests that will be applied to pull requests before they are merged, i.e., backends where we expect that introducing, e.g., a transcription error changing `+` to `*` will result in our CI failing.

Is there a way to add a test to our CI that runs our code against the Zig crypto test-suite?

**Comment by jedisct1** [comment]
Oh, absolutely, I can add that!

**Comment by jedisct1** [comment]
Meanwhile, the check mark has been replaced by the white one.

**Comment by JasonGross** [comment]
Great, thanks!  Could I trouble you too provide links to Zig's CI (if it's public) and to the part of the standard library that includes fiat-crypto (I couldn't find it with a brief Google search)

**Comment by jedisct1** [comment]
Zig uses multiple CI systems, but this is the [main one](https://dev.azure.com/ziglang/zig/_build?definitionId=1&_a=summary&repositoryFilter=1&branchFilter=5%2C5%2C5%2C5%2C5%2C5%2C5%2C5), used to test Linux, macOS and Windows builds.

The first bits using Fiat-crypto are [here](https://github.com/ziglang/zig/tree/master/lib/std/crypto/pcurves) (generated file [here](https://github.com/ziglang/zig/blob/master/lib/std/crypto/pcurves/p256/p256_64.zig)) and other curves will follow quickly.

**Comment by jedisct1** [comment]
The generated code is now directly tested in fiat-crypto's CI:

https://github.com/mit-plv/fiat-crypto/blob/master/fiat-zig/src/main.zig

in addition to the inversion code, that is also part of what is run by CI.

These tests are run in debug mode, which checks for arithmetic overflow. And will also check for unexpected truncation with help of #939

**Pull request merged**
