### PR TITLE
Add x25519 donna versions with the new way of generating C code

### PR DESCRIPTION
**Pull request by JasonGross**
See #294.

This is kludgy, and perhaps we should update `X25519/C*` versions instead.

### CODE REVIEW

**Comment by davidben** [comment]
By the way, I haven't fully unpacked what's going on here, but I think the difference between the synthesized code and donna is that donna does the 0x13 multiplication earlier as a `uint64_t` (which fits because 51 bits leaves enough room), while the synthesized code does that multiplication after we've done enough other work that it's a `uint128_t`.

That is, the synthesized code computes:

```
uint64_t a, b, c, d;
uint128_t ab = (uint128_t)a * b;
uint128_t cd = (uint128_t)c * d;
uint128_t abcd = ab + cd;
uint128_t abcd19 = 0x13 * abcd;
```

Whereas donna computes:

```
uint64_t a, b, c, d;
uint64_t a19 = 0x13 * a;  // This is okay because a is 51-bit
uint64_t c19 = 0x13 * c;  // This is okay because c is 51-bit
uint128_t ab19 = (uint128_t)a19 * b;
uint128_t cd19 = (uint128_t)c19 * d;
uint128_t abcd19 = ab19 + cd19;
```

Notably the synthesized code multiples one `uint128_t` by 19 rather than two `uint64_t`s. This seems to frustrate the compiler's ability to optimize multiplying by 19, since `uint128_t` is not the natural word size.

**Comment by davidben** [comment]
I believe the compiler also can't do this transformation itself because it doesn't know `19 * a` as a `uint64_t` does not overflow. (Though if I add a check, it still doesn't perform this transformation. I suspect `uint128_t`s are only minimally optimized.)

**Comment by davidben** [comment]
Oh, and a second trick donna does is once you perform that transformation, CSE gets to take another pass because `a19` and `c19` are used a couple of times.

**Comment by JasonGross** [comment]
We very nearly have a CSE pass; I believe the main issue is that I haven't read Adam's proof of correctness from lambda-tamer closely enough to see why it is easy, so there are a few lingering cases that I haven't yet pushed through in the proof.

The other transformation is a bit tricker to specify, and it's not entirely clear to me what it should be.  Something like "if we find a node `c * x` for some constant `c`, and we find that all references to `x` across the entire program are `c * x`, and `x` is defined as `y + z` where `y` and `z` are both of the form `a * b` (not necessarily for the same `a` and `b`) and the bit-width on `c * a * b` is the same as the bitwidth of `a * b` and larger than either the bitwidth of `c * a` or `c * b`, and this holds for both the constituents of `y` and the constituents of `z`, then we can bind a fresh variable to `c * a` (or `c * b`) for each of `y` and `z`, bind fresh variables for `cy` and `cz`, and replace the binding of `c * x` with a binding of `cy + cz`" would work, but is very convoluted.  Moreover, it requires at least two passes: one pass to annotate each variable with the number of occurrences, and a second pass to do the replacement.  Perhaps a better strategy would involve a different representation of arithmetic expressions and some sort of bounds-aware pass out of that?

**Comment by davidben** [comment]
Do you actually need to count occurrences? Even if it didn't get to do CSE, I expect two 19 * u64 -> u64 operations is already going to faster than one 19 * u128 -> u128, when the native word size is u64. In the latter, I still need to multiply 19 by low and high u64s, but I have to deal with carries from the former to the latter rather than discarding the top word. (The tricks the compiler does to multiply by 19 don't give back the high word.)

**Comment by davidben** [comment]
(To be clear, I'm perfectly happy with just using the manual scheduling. If closing that gap isn't very interesting, don't take this as a request or anything.)

**Comment by JasonGross** [comment]
No, we don't need to count occurences.  We'd still want to do dead code elimination, but, hm, I guess if each variable node stored it's value one and two levels deeper, it wouldn't be too hard to identify `19 * (a * b + c * d)` and change it to `19 * a * b + 19 * c * d`.  I'd expect it to take me about two days to write the PHOAS pass and another week or two to prove it correct.  It's not currently on my todo list, but feel free to open an issue to track this, or to undertake it yourself :-)

**Pull request merged**
