### PR TITLE
Make hint globality explicit

### PR DESCRIPTION
**Pull request by JasonGross**
This is mostly an adaptation for coq/coq#16004

We also make some other warnings into errors at the same time.

### CODE REVIEW

**Comment by JasonGross** [comment]
I think this doesn't pass on the bedrock folder.  If someone else could finish this PR up for me (or if @Alizter or @ppedrot has a script they've been using to generate overlays automatically from the warnings), I'd be very appreciative.  (This PR is just about adding `#[global]` or whatever before all the hints, and is not doing the strict hint behavior dance.)

**Comment by JasonGross** [comment]
Maybe someone can figure out which Instances I incorrectly made global when they should be local, or whatever, that broke some of the bedrock code?

**Comment by JasonGross** [comment]
<details><summary>build log of the failing bits of bedrock</summary>

```
COQDEP VFILES
make[3]: Nothing to be done for 'real-all'.
COQC src/Bedrock/Field/Interface/Compilation2.v
COQC src/Bedrock/End2End/X25519/Field25519.v
COQC src/Bedrock/Field/Synthesis/Examples/X25519_64.v
COQC src/Bedrock/Field/Synthesis/Examples/X1305_32.v
File "./src/Bedrock/Field/Interface/Compilation2.v", line 145, characters 4-27:
Error:
In environment
width : Z
BW : Bitwidth width
word : Interface.word width
mem : map.map word.rep Init.Byte.byte
locals : map.map string word.rep
env : map.map string (list string * list string * cmd)
ext_spec : Semantics.ExtSpec
word_ok : word.ok word
mem_ok : map.ok mem
locals_ok : map.ok locals
env_ok : map.ok env
ext_spec_ok : Semantics.ext_spec.ok ext_spec
field_parameters : FieldParameters
field_representaton : FieldRepresentation
field_representation_ok : FieldRepresentation_ok
name : string
op : BinOp name
tr : Semantics.trace
m : map.rep
l : map.rep
functions : list (string * (list string * list string * cmd))
x, y : F M_pos
v := bin_model x y : F M_pos
P : F M_pos -> Type
pred : P v -> predicate
k : nlet_eq_k P v
k_impl : cmd
Rin, Rout : map.rep -> Prop
out : F M_pos
x_ptr : word.rep
x_var : string
y_ptr : word.rep
y_var : string
out_ptr : word.rep
out_var : string
bound_out : option bounds
H : spec_of_UnOp un_to_mont functions
H0 : map.get l out_var = Some out_ptr
x1 : felem
H1 : feval x1 = out
H9 : maybe_bounded bound_out x1
H8 : (Field.FElem out_ptr x1 ⋆ Rout) m
x0 : felem
H2 : feval x0 = x
H7 : maybe_bounded (Some bin_xbounds) x0
x2 : felem
H6 : feval x2 = y
H11 : maybe_bounded (Some bin_ybounds) x2
H10 : (Field.FElem y_ptr x2 ⋆ (Rin ⋆ Field.FElem x_ptr x0)) m
H3 : map.get l x_var = Some x_ptr
H4 : map.get l y_var = Some y_ptr
H5 : forall m' : map.rep,
     (Lift1Prop.ex1
        (fun v' : felem =>
         emp (feval v' = v /\ maybe_bounded (Some bin_outbounds) v')
         ⋆ Field.FElem out_ptr v') ⋆ Rout) m' ->
     <{ Trace := tr; Memory := m'; Locals := l; Functions := functions }>
       k_impl
     <{ pred (k v eq_refl) }>
args := [out_ptr; x_ptr; y_ptr] : list word.rep
Unable to unify
 "forall (pout px : word.rep) (out x : felem) (Rr : map.rep -> Prop)
    (tr : Semantics.trace) (mem0 : map.rep),
  bounded_by un_xbounds x /\
  (exists Ra : map.rep -> Prop, (Field.FElem px x ⋆ Ra) mem0) /\
  (Field.FElem pout out ⋆ Rr) mem0 ->
  WeakestPrecondition.call functions name tr mem0 [
    pout; px]
    (fun (tr' : Semantics.trace) (mem' : map.rep) (rets : list word.rep) =>
     rets = [] /\
     tr = tr' /\
     (exists out0 : felem,
        feval out0 = un_model (feval x) /\
        bounded_by un_outbounds out0 /\ (Field.FElem pout out0 ⋆ Rr) mem'))"
with
 "(fix call (functions : list (string * (list string * list string * cmd))) :
       string ->
       Semantics.trace ->
       map.rep ->
       list word.rep ->
       (Semantics.trace -> map.rep -> list word.rep -> Prop) -> Prop :=
     WeakestPrecondition.call_body call functions) functions name tr m args
    ?x".

Command exited with non-zero status 1
src/Bedrock/Field/Interface/Compilation2.vo (real: 3.66, user: 2.86, sys: 0.56, mem: 602108 ko)
make: *** [Makefile.coq:792: src/Bedrock/Field/Interface/Compilation2.vo] Error 1
COQC src/Bedrock/Field/Synthesis/Examples/p224_64.v
File "./src/Bedrock/Field/Synthesis/Examples/X1305_32.v", line 20, characters 7-23:
Error: Tactic failure: Proof search failed.

Command exited with non-zero status 1
src/Bedrock/Field/Synthesis/Examples/X1305_32.vo (real: 24.94, user: 23.65, sys: 1.02, mem: 1096724 ko)
make: *** [Makefile.coq:793: src/Bedrock/Field/Synthesis/Examples/X1305_32.vo] Error 1
COQC src/Bedrock/Field/Synthesis/Examples/p224_64_new.v
Finished transaction in 44.461 secs (44.128u,0.303s) (successful)
File "./src/Bedrock/Field/Synthesis/Examples/p224_64.v", line 16, characters 2-18:
Error: Tactic failure: Proof search failed.

Command exited with non-zero status 1
src/Bedrock/Field/Synthesis/Examples/p224_64.vo (real: 87.91, user: 85.56, sys: 2.08, mem: 1460688 ko)
make: *** [Makefile.coq:793: src/Bedrock/Field/Synthesis/Examples/p224_64.vo] Error 1
COQC src/Bedrock/Field/Synthesis/Examples/p256_64.v
File "./src/Bedrock/Field/Synthesis/Examples/X25519_64.v", line 20, characters 7-23:
Error: Tactic failure: Proof search failed.

Command exited with non-zero status 1
src/Bedrock/Field/Synthesis/Examples/X25519_64.vo (real: 106.13, user: 104.76, sys: 1.19, mem: 1203036 ko)
make: *** [Makefile.coq:793: src/Bedrock/Field/Synthesis/Examples/X25519_64.vo] Error 1
Finished transaction in 5.082 secs (5.082u,0.s) (successful)
Finished transaction in 6.706 secs (6.705u,0.001s) (successful)
Finished transaction in 3.36 secs (3.359u,0.001s) (successful)
Finished transaction in 6.932 secs (6.905u,0.026s) (successful)
Finished transaction in 15.057 secs (15.039u,0.017s) (successful)
File "./src/Bedrock/Field/Synthesis/Examples/p256_64.v", line 16, characters 8-24:
Error: Tactic failure: Proof search failed.

Command exited with non-zero status 1
src/Bedrock/Field/Synthesis/Examples/p256_64.vo (real: 66.10, user: 65.17, sys: 0.69, mem: 1424192 ko)
make: *** [Makefile.coq:793: src/Bedrock/Field/Synthesis/Examples/p256_64.vo] Error 1
Finished transaction in 11.986 secs (11.977u,0.008s) (successful)
Finished transaction in 5.436 secs (5.411u,0.02s) (successful)
Finished transaction in 6.778 secs (6.778u,0.s) (successful)
Finished transaction in 12.953 secs (12.953u,0.s) (successful)
src/Bedrock/End2End/X25519/Field25519.vo (real: 217.13, user: 215.24, sys: 1.68, mem: 1546660 ko)
Finished transaction in 186.609 secs (185.867u,0.739s) (successful)
Finished transaction in 1.029 secs (1.029u,0.s) (successful)
Finished transaction in 0.837 secs (0.837u,0.s) (successful)
Finished transaction in 52.467 secs (52.448u,0.017s) (successful)
Finished transaction in 52.955 secs (52.915u,0.039s) (successful)
Finished transaction in 0.297 secs (0.297u,0.s) (successful)
Finished transaction in 0.242 secs (0.242u,0.s) (successful)
src/Bedrock/Field/Synthesis/Examples/p224_64_new.vo (real: 708.73, user: 706.40, sys: 2.09, mem: 2809796 ko)
make: Target 'coq' not remade because of errors.
```
</details>

**Comment by JasonGross** [comment]
We should also run a bench before merging to make sure I didn't slow anything down.

**Comment by ppedrot** [comment]
With @Alizter we've been using a script indeed, otherwise you get wrong results with sed only. The script is available somewhere following a Coq discourse link, but for efficiency I can write the overlay myself.

**Comment by JasonGross** [comment]
@ppedrot If you're willing to write the overlay for fiat-crypto, rupicola, engine-bench, and fiat, I'd be very appreciative, and will merge the PRs as soon as CI passes (for fiat I'll tag a version for old compatibility and drop the older versions on CI).  (For fiat-crypto-legacy, I'm still optimistic about getting https://github.com/mit-plv/fiat-crypto/pull/1310 working.)  For fiat-crypto, you probably want to run on top of https://github.com/mit-plv/fiat-crypto/pull/1312 (hopefully it'll be auto-merged soon), as on master we're currently suppressing the relevant warnings.

**Pull request closed without merging**
