### PR TITLE
Update Makefile

### PR DESCRIPTION
**Pull request by andres-erbsen**

### CODE REVIEW

**Comment by andres-erbsen** [comment]
https://github.com/mit-plv/fiat-crypto/compare/fancy_cleanup shows coqproject updates, are we looking at the same thing?

**Comment by JasonGross** [comment]
This is a PR on fancy_cleanup-makefile-fix, not fancy_cleanup.

**Comment by andres-erbsen** [comment]
"andres-erbsen wants to merge 1 commit into fancy_cleanup from fancy_cleanup-makefile-fix"

**Comment by JasonGross** [comment]
Oh, I see.  Mobile view doesn't show the base branch, so never mind

**Comment by andres-erbsen** [comment]
Well, anyway, what I am trying to do here does not seem to be working. @JasonGross could you take a look? Jade's branch seems to have mysterious issues with make not running coq files in the right order.

**Comment by JasonGross** [comment]
The Travis log says
```
COQDEP VFILES
File "src/Fancy/Barrett256.v", characters 17280-17280: Syntax error
```
If any file has a syntax error bad enough to make coqdep barf, the dependencies get all screwed up.

**Comment by andres-erbsen** [comment]
Thanks!

**Comment by jadephilipoom** [comment]
That seems to have fixed it, Jason, thanks!

**Pull request closed without merging**
