### PR TITLE
Add poly1305

### LINKED ISSUE #761: feature request: bedrock2 32-bit poly1305

### PR DESCRIPTION
**Pull request by JasonGross**
This was somewhat more annoying than it had to be; I'd like to come up
with a more compact format for specifying the primes that we're building
by default.

Partial progress on #761

```
    Time | Peak Mem | File Name
-----------------------------------------------------
0m02.46s | 20076 ko | Total Time / Peak Mem
-----------------------------------------------------
0m00.34s | 17136 ko | fiat-c/src/poly1305_32.c
0m00.34s | 17552 ko | fiat-rust/src/poly1305_32.rs
0m00.33s | 17152 ko | fiat-java/src/FiatPoly1305.java
0m00.31s | 16884 ko | fiat-go/src/poly1305_32.go
0m00.29s | 17300 ko | fiat-go/src/poly1305_64.go
0m00.27s | 16680 ko | fiat-rust/src/poly1305_64.rs
0m00.26s | 16608 ko | fiat-c/src/poly1305_64.c
0m00.21s | 20076 ko | fiat-bedrock2/src/poly1305_32.c
0m00.12s | 17388 ko | fiat-bedrock2/src/poly1305_64.c
```

### CODE REVIEW

**Comment by jadephilipoom** [comment]
Note that this adds the bedrock2 translation of generated code to the CI, but does not include a correctness proof. @andres-erbsen, did you mean the correctness proof as well in #761?

**Comment by andres-erbsen** [comment]
Yes, I meant in-Coq output that I could later feed into the bedrock2->riscv compiler inside Coq. My apologies for not specifying.

**Comment by jadephilipoom** [comment]
I think we should still merge this but not close the issue. Jason, can you change the PR comment so the issue doesn't close when it's merged?

**Comment by JasonGross** [comment]
Updated

**Pull request merged**
