### PR TITLE
[coq] Adapt to coq/coq#11980 : Improvements on Print Assumptions

### PR DESCRIPTION
**Pull request by ejgallego**
Please merge [for Coq's master CI].

### CODE REVIEW

**Comment by JasonGross** [comment]
This is not backwards compatible.  Perhaps instead there are some options we can pass to `diff` to get it to ignore whitespace including new lines?  Or else can we emit a `Set Printing Width` command to make `Print Assumptions` print each type on a single line?

**Comment by ejgallego** [comment]
> This is not backwards compatible. Perhaps instead there are some options we can pass to `diff` to get it to ignore whitespace including new lines? Or else can we emit a `Set Printing Width` command to make `Print Assumptions` print each type on a single line?

I'm afraid we cannot provide user-level output compatibility upstream; I think the simplest approach is to only run output tests for Coq `master`

**Comment by JasonGross** [comment]
Let's try #794 instead

**Comment by ejgallego** [comment]
> Let's try #794 instead

Thanks @JasonGross , that seems a bit overkill tho; maybe you could use something like `patdiff` if you don't care about spacing?

**Pull request closed without merging**
