### PR TITLE
CSE modulo arithmetic without inlining

### PR DESCRIPTION
**Pull request by JasonGross**
This takes care of most of #158.  The remaining bits are reworking the Wf and interpretation lemmas to actually work.  (The former needs a only bit of rethinking and rephrasing to handle the fact that sometimes we change the stored symbolic expression from a complicated one to a fresh variable, while the latter needs major surgery, which Adam tells me is easy.)

### CODE REVIEW

**Comment by andres-erbsen** [comment]
LGTM NT.

**Comment by JasonGross** [comment]
NT?

**Comment by andres-erbsen** [comment]
I didn't run the tests (but now travis has passed anyway).

**Comment by JasonGross** [comment]
So it means "not tested" or "no tests"?

**Pull request merged**
