### PR TITLE
Remove special conditional subtract

### PR DESCRIPTION
**Pull request by JasonGross**
This is on top of #97.  Here's the current list of `Print Assumptions` in 8.6:
```coq
Axioms:
WordUtil.wlast_combine : forall (sz : nat) (a : Word.word sz) (b : bool),
                         WordUtil.wlast (Word.combine a (Word.WS b Word.WO)) =
                         b
WordUtil.wlast : forall sz : nat, Word.word (sz + 1) -> bool
WordUtil.winit_combine : forall (sz : nat) (a : Word.word sz)
                           (b : Word.word 1),
                         WordUtil.winit (Word.combine a b) = a
WordUtil.winit : forall sz : nat, Word.word (sz + 1) -> Word.word sz
shiftr_range : forall a n m : Z,
               (0 <= a < 2 ^ (n + m))%Z -> (0 <= Z.shiftr a n < 2 ^ m)%Z
GF25519BoundedCommon.proof_admitted : False
 used in postfreezeW_subproof to prove: GF25519BoundedCommon.fe25519W ->
                                        GF25519BoundedCommon.fe25519W
prime_q : Znumtheory.prime (2 ^ 255 - 19)
prime_l : Znumtheory.prime (2 ^ 252 + 27742317777372353535851937790883648493)
pow2_mod_range : forall a n m : Z,
                 (n <= m)%Z -> (0 <= ZUtil.Z.pow2_mod a n < 2 ^ m)%Z
GF25519BoundedCommon.postfreezeW_correct_and_bounded :
forall x : GF25519BoundedCommon.fe25519W,
GF25519BoundedCommon.is_bounded (GF25519BoundedCommon.fe25519WToZ x) = true ->
GF25519BoundedCommon.fe25519WToZ (GF25519BoundedCommon.postfreezeW x) =
GF25519BoundedCommon.postfreeze (GF25519BoundedCommon.fe25519WToZ x) /\
GF25519BoundedCommon.is_bounded
  (GF25519BoundedCommon.fe25519WToZ (GF25519BoundedCommon.postfreezeW x)) =
true
GF25519BoundedCommon.postfreeze : GF25519.fe25519 -> GF25519.fe25519
Tuple.map_S : forall (n : nat) (A B : Type) (f : A -> B)
                (xs : Tuple.tuple' A n) (x : A),
              Tuple.map f (xs, x) = (Tuple.map f xs, f x)
Tuple.map2_S : forall (n : nat) (A B C : Type) (f : A -> B -> C)
                 (xs : Tuple.tuple' A n) (ys : Tuple.tuple' B n)
                 (x : A) (y : B),
               Tuple.map2 f (xs, x) (ys, y) = (Tuple.map2 f xs ys, f x y)
GF25519BoundedCommon.freeze_prepost_freeze : forall
                                               x :
                                                Z * Z * Z * Z * Z * Z * Z * Z *
                                                Z * Z,
                                             GF25519BoundedCommon.postfreeze
                                               (GF25519BoundedCommon.prefreeze
                                                 x) =
                                             GF25519.freeze x
WordUtil.combine_winit_wlast : forall (sz : nat) (a : Word.word sz)
                                 (b : Word.word 1)
                                 (c : Word.word (sz + 1)),
                               Word.combine a b = c <->
                               a = WordUtil.winit c /\
                               b = Word.WS (WordUtil.wlast c) Word.WO
WordNZ_split2 : forall (n m : nat) (w : Word.word (n + m)),
                Z.of_N (Word.wordToN (Word.split2 n m w)) =
                Z.shiftr (Z.of_N (Word.wordToN w)) (Z.of_nat n)
WordNZ_split1 : forall (n m : nat) (w : Word.word (n + m)),
                Z.of_N (Word.wordToN (Word.split1 n m w)) =
                ZUtil.Z.pow2_mod (Z.of_N (Word.wordToN w)) (Z.of_nat n)
WordNZ_range_mono : forall (n : nat) (m : Z) (w : Word.word n),
                    (Z.of_nat n <= m)%Z ->
                    (0 <= Z.of_N (Word.wordToN w) < 2 ^ m)%Z
WordNZ_range : forall (n : nat) (B : Z) (w : Word.word n),
               (2 ^ Z.of_nat n <= B)%Z ->
               (0 <= Z.of_N (Word.wordToN w) < B)%Z
Proper_sqrt : Proper (GF25519BoundedCommon.eq ==> GF25519BoundedCommon.eq)
                GF25519Bounded.sqrt
H : forall n : nat, Word.word n -> Word.word (b + b)
B_order_l : CompleteEdwardsCurveTheorems.E.eq
              (CompleteEdwardsCurve.E.mul (Z.to_nat l) B)
              CompleteEdwardsCurve.E.zero
```
(There are also a bunch of `admit`s from `feDec_correct` in 8.4 only.)

Just in case you're curious where the time in `Experiments/Ed25519.v` is spent in 8.6:
```
total time:     35.736s

 tactic                                   local  total   calls       max
────────────────────────────────────────┴──────┴──────┴───────┴─────────┘
─destruct X eqn:? ----------------------  16.3%  16.3%       2    2.920s
─destruct (ModularBaseSystemListProofs.g  14.6%  14.6%       1    5.228s
─discriminate --------------------------  10.7%  10.7%       7    1.964s
─vm_decide -----------------------------   8.9%   9.0%      22    3.144s
─rewrite Hgm in * ----------------------   6.7%   6.7%       1    2.392s
─omega ---------------------------------   3.4%   3.4%     470    0.340s
─rewrite Tuple.to_list_from_list -------   3.4%   3.4%      14    0.408s
─rewrite A in * ------------------------   3.4%   3.4%       1    1.212s
─vm_decide_no_check --------------------   0.0%   2.0%      26    0.660s
─apply dec_bool ------------------------   1.9%   2.0%      27    0.660s
```

### CODE REVIEW

**Comment by jadephilipoom** [comment]
Why is Travis failing on the last two commits?

**Comment by JasonGross** [comment]
It's not?

image

It's failing on the first two commits, though, because I hadn't yet pushed the 8.4 fix for universes.

**Comment by jadephilipoom** [comment]
Oops, misunderstood the order there. Never mind. :)

**Comment by JasonGross** [comment]
Merged via #104

**Pull request closed without merging**
