### PR TITLE
Coq PR# 9918 overlay: add -no-template-check

### PR DESCRIPTION
**Pull request by mattam82**
Same story as mit-plv/fiat#28 adapt to coq/coq#9918

### CODE REVIEW

**Comment by JasonGross** [comment]
Is it possible to fix fiat-crypto without relying on unsound flags?  Unlike fiat, fiat-crypto shouldn't be relying on being able to instantiate fancy inductives with Prop/Set.  I'd be fine with a fix that, e.g., replaces all instances of Set with Type or something.

**Comment by mattam82** [comment]
It's certainly doable but requires moving the inductive declarations that you want to be template-polymorphic outside of sections: i.e. make the parameterization explicit when you define them. It will be backward compatible.

**Comment by JasonGross** [comment]
That should be fine.  Which inductives are problematic?

**Comment by mattam82** [comment]
I don't know, for sure things in Parsing rely on polymorphism. It's easy to check, just remove the flag and see where you get typing errors, they will involved inductives that are no longer seen as template polymorphic with the new criterion.

**Comment by JasonGross** [comment]
It looks like only a small change was needed for fiat-crypto: #568.  I will merge that as soon as the CI passes

**Comment by JasonGross** [comment]
I've now merged #568, so this is no longer needed

**Pull request closed without merging**
