### PR TITLE
try to work around coq #8457

### PR DESCRIPTION
**Pull request by andres-erbsen**

### CODE REVIEW

**Comment by JasonGross** [comment]
Why not just `generalize m_big; intros _`?

**Comment by andres-erbsen** [comment]
Because I didn't remember whether this is actually preserved after section close, and couldn't find documentation to look it up, and didn't want to build the PR branch of coq to test.

**Comment by JasonGross** [comment]
I think the relevant condition is "does the tactic modify the proof term?".  `change` doesn't, I think almost every other tactics that touches the goal or the context does.

**Comment by vbgl** [comment]
Does this work? I get the following error:

```
File "./src/Specific/NISTP256/AMD128/Synthesis.v", line 6, characters 9-31:
Error:
In nested Ltac calls to "make_Synthesis_package", 
"get_Synthesis_package", "add_Synthesis_package",
"MontgomeryPackage.add_Montgomery_package",
"MontgomeryPackage.add_nonzero_ext", "CurveParametersPackage.if_montgomery",
"tac_true" (bound to
fun _ =>
  let r := TagList.Tag.get pkg BasePackage.TAG.r in
  let sz := TagList.Tag.get pkg CurveParameters.TAG.sz in
  let m := TagList.Tag.get pkg BasePackage.TAG.m in
  let m_enc := TagList.Tag.get pkg BasePackage.TAG.m_enc in
  let r' := TagList.Tag.get pkg MontgomeryPackage.TAG.r' in
  let m_enc_correct_montgomery :=
   TagList.Tag.get pkg MontgomeryPackage.TAG.m_enc_correct_montgomery
  in
  let r'_pow_correct :=
   TagList.Tag.get pkg MontgomeryPackage.TAG.r'_pow_correct
  in
  let r_big := TagList.Tag.get pkg MontgomeryPackage.TAG.r_big in
  let m_big := TagList.Tag.get pkg MontgomeryPackage.TAG.m_big in
  let montgomery_to_F :=
   TagList.Tag.get pkg MontgomeryPackage.TAG.montgomery_to_F
  in
  let nonzero_ext := fresh "nonzero_ext" in
  let nonzero_ext :=
   Montgomery.pose_nonzero_ext r sz m m_enc r' m_enc_correct_montgomery
    r'_pow_correct r_big m_big montgomery_to_F nonzero_ext
  in
  TagList.Tag.update pkg MontgomeryPackage.TAG.nonzero_ext nonzero_ext),
"Montgomery.pose_nonzero_ext" and
"(Montgomery.nonzero_ext_gen r sz m m_enc r' m_enc_correct_montgomery
    r'_pow_correct r_big m_big)" (with sz:=sz, r_big:=r_big,
r'_pow_correct:=r'_pow_correct, r':=r', r:=r,
montgomery_to_F:=montgomery_to_F,
m_enc_correct_montgomery:=m_enc_correct_montgomery, m_enc:=m_enc,
m_big:=m_big, m:=m), last term evaluation failed.
Illegal application (Non-functional construction): 
The expression
 "Montgomery.nonzero_ext_gen r sz m m_enc r' m_enc_correct_montgomery
    r'_pow_correct r_big" of type
 "{f : Tuple.tuple BinNums.Z sz -> BinNums.Z |
  let eval := MontgomeryAPI.eval (BinNums.Zpos r) in
  forall A : Tuple.tuple BinNums.Z sz,
  UniformWeight.small (BinNums.Zpos r) A ->
  BinInt.Z.lt (eval A) (eval m_enc) ->
  f A = BinNums.Z0 <->
  Montgomery.montgomery_to_F_gen sz m r' (eval A) =
  ModularArithmetic.F.of_Z m BinNums.Z0}"
cannot be applied to the term
 "m_big" : "BinInt.Z.lt (BinNums.Zpos BinNums.xH) (BinNums.Zpos m)"
```

**Comment by fajb** [comment]
@andres-erbsen indeed found the origin of the problem.
Yet, a similar patch needs to be applied to the 'nonzero_ext_gen' function.

You, Ltac gurus, know the best way to do it but adding a 'generalize m_big' for 'nonzero_ext_gen' and 
'add_ext_gen' works for me.

@andres-erbsen , thanks again.

**Comment by andres-erbsen** [comment]
Superseded by #445

**Pull request closed without merging**
